version: '3'

services:
  db:
    #container_name: mariadb
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Mysql@2021
    env_file:
      - db.env

  redis:
    #container_name: app_redis
    image: redis:alpine
    restart: always

  app:
    #container_name: app_nextcloud
    build: ./nextcloud
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - VIRTUAL_HOST=drive.domain.com
      - LETSENCRYPT_HOST=drive.domain.com
      - LETSENCRYPT_EMAIL=contact@domain.com
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis
    networks:
      - proxy-tier
      - default

  cron:
    #container_name: app_cron
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  proxy:
    #container_name: proxy_http
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    #container_name: app_letsencrypt
    #image: jrcs/letsencrypt-nginx-proxy-companion
    build: ./letsencrypt
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy
      
  zbx-server:
    #container_name: zbx-server
    image: zabbix/zabbix-server-mysql:ol-5.0-latest
    restart: always
    ports: 
      - 10051:10051
    environment:
      - DB_SERVER_HOST=db
      - MYSQL_ROOT_PASSWORD=Mysql@2021
      - ZBX_STARTPOLLERS=5
    env_file: 
      - zbx.env
    depends_on: 
      - db
    volumes:
      - '/etc/zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
    links: 
      - db

# ZABBIX    
  zbx-front: 
    #container_name: zbx-frontend
    image: zabbix/zabbix-web-apache-mysql:ol-5.0-latest
    restart: always
    #ports:
    #  - 8080:8080
    #  - 8443:8443
    environment:
      - VIRTUAL_HOST=zabbix.domain.com
      - VIRTUAL_PORT=8080 
      - LETSENCRYPT_HOST=zabbix.domain.com
      - LETSENCRYPT_EMAIL=contact@domain.com
      - DB_SERVER_HOST=db
      - MYSQL_ROOT_PASSWORD=Mysql@2021
      - PHP_TZ=America/Bahia
      - ZBX_SERVER_HOST=zbx-server
      - ZBX_SERVER_NAME=Empresa
    env_file: 
      - zbx.env
    depends_on: 
      - db
    #links: 
    #  - db
    networks:
      - proxy-tier
      - default

  zbx-agent:
    image: zabbix/zabbix-agent:ol-5.0-latest
    restart: always
    environment: 
      - ZBX_HOSTNAME=zbx-agent-docker
      - ZBX_SERVER_HOST=zbx-server
    depends_on:
      - zbx-server
    volumes: 
      - /etc/zabbix/zabbix_agent.d:/etc/zabbix/zabbix_agentd.d
    networks:
      - default

  glpi:
    #container_name: app_glpi
    image: diouxx/glpi
    hostname: glpi
    #ports:
    #  - "81:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/www/html/glpi/:/var/www/html/glpi
    environment:
      - VIRTUAL_HOST=suport.domain.com
      - LETSENCRYPT_HOST=suport.domain.com
      - LETSENCRYPT_EMAIL=contact@domain.com
      - MYSQL_ROOT_PASSWORD=Mysql@2021
      - TIMEZONE=America/Bahia
    restart: always
    env_file: 
      - glpi.env
    #links: 
    #  - db
    networks:
      - proxy-tier
      - default

# GRAYLOG
  mongo:
    image: mongo:4.2
    restart: always
    volumes:
      - /var/docker/graylog/mongo/data:/data/db

  elasticsearch:
    image:  docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    restart: always
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
#     - network.host=0.0.0.0
      - ES_JAVA_OPTS=-Xms512m -Xmx512m      
      - discovery.type=single-node    
    volumes:
      - /var/docker/graylog/elasticsearch/data:/usr/share/elasticsearch/data  
  
  graylog:
    image: graylog/graylog:4.1    
    restart: always    
    environment:
      - VIRTUAL_HOST=logs.ctsnetworks.com.br      
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=logs.ctsnetworks.com.br      
      - LETSENCRYPT_EMAIL=suporte@t3tecnologia.com.br      
      - GRAYLOG_PASSWORD_SECRET=graylog@2021@agora
      - GRAYLOG_ROOT_PASSWORD_SHA2=498d052d06f5fc8247d1964bd8257448c1dec61e8304ab6b2f62290beb3eb500      
      - GRAYLOG_HTTP_EXTERNAL_URI=https://logs.ctsnetworks.com.br/
#     - GRAYLOG_WEB_ENDPOINT_URI=http://graylog:9000/api    
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    volumes:           
      - graylog:/usr/share/graylog/data/journal
      - /var/docker/graylog/plugin:/usr/share/graylog/plugin    
    ports:      
      - 1514:1514        # SYSLOG TCP
      - 1514:1514/udp    # SYSLOG UDP
      - 12201:12201      # GELF   TCP
      - 12201:12201/udp  # GELP   UDP  
    links:      
      - mongo
      - elasticsearch    
    networks:      
      - proxy-tier
      - default
    
  #pbs:
  #  image: ayufan/proxmox-backup-server:latest
  #  hostname: pbs-server
  #  ports:
  #    - 8007:8007
  #  volumes: 
  #    - /etc/proxmox-backup:/etc/proxmox-backup
  #    - /var/log/proxmox-backup:/var/log/proxmox-backup
  #    - /var/lib/proxmox-backup:/var/lib/proxmox-backup
    #environment:
      #- VIRTUAL_HOST=pbs.domain.com
      #- VIRTUAL_PORT=8007
      #- LETSENCRYPT_HOST=pbs.domain.com
      #- LETSENCRYPT_EMAIL=contact@domain.com
  #  networks:
  #    default

  grafana:
    #container_name: app_grafana
    image: grafana/grafana
    #ports: 
    #  - "3000:3000"
    restart: always
    volumes: 
      - /home/mauricio/docker/grafana/data:/var/lib/grafana
    environment:
      - VIRTUAL_HOST=grafana.domain.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=grafana.domain.com
      - LETSENCRYPT_EMAIL=contact@domain.com
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    networks:
      - proxy-tier
      - default

volumes:
  db:
  nextcloud:
  certs:
  vhost.d:
  html:
  graylog:

networks:
  proxy-tier:
