version: '3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Mysql@2021
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - VIRTUAL_HOST=localhost
      - LETSENCRYPT_HOST=localhost
      - LETSENCRYPT_EMAIL=localhost
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis
    networks:
      - proxy-tier
      - default

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy
      
  zbx-server:
    image: zabbix/zabbix-server-mysql:ol-5.0-latest
    restart: always
    ports: 
      - 10051:10051
    environment: 
      - DB_SERVER_HOST=db
      - MYSQL_ROOT_PASSWORD=Msyql@2021
      - ZBX_STARTPOLLERS=5
    env_file: 
      - zbx.env
    depends_on: 
      - db
    volumes:
        - '/etc/zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
    links: 
      - db

  zbx-front: 
    image: zabbix/zabbix-web-apache-mysql:ol-5.0-latest
    restart: always
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      - MYSQL_ROOT_PASSWORD=Mysql@2021
      - PHP_TZ=America/Bahia
      - ZBX_SERVER_HOST=zbx-server
      - DB_SERVER_HOST=db
    env_file: 
      - zbx.env
    depends_on: 
      - db
    links: 
      - db

  glpi:
    image: diouxx/glpi
    container_name : glpi
    hostname: glpi
    #ports:
    #  - "81:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/www/html/glpi/:/var/www/html/glpi
    environment:
      - MYSQL_ROOT_PASSWORD=Mysql@2021
      - TIMEZONE=America/Bahia
    restart: always
    env_file: 
      - glpi.env
    links: 
      - db

volumes:
  db:
  nextcloud:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:
