{
 "title": "SIP Error Rates",
 "tags": [ "sip" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "INVITE Server Errors (50.*)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum by(target_name) (rate(heplify_method_response{method=\"INVITE\", response=~\"50.*\"}[10m])) / \nsum by(target_name) (rate(heplify_method_response{method=\"INVITE\", response=\"INVITE\"}[10m])) * 100 \nand sum by(target_name) (rate(heplify_method_response{method=\"INVITE\", response=\"INVITE\"}[10m])) > 0.2) > 1",
     "legendFormat": "{{target_name}}"
    }
   ]
  },
  {
   "title": "INVITE 403",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum by(target_name) (rate(heplify_method_response{method=\"INVITE\", response=\"403\"}[10m])) / \nsum by(target_name) (rate(heplify_method_response{method=\"INVITE\", response=\"INVITE\"}[10m])) * 100 \nand sum by(target_name) (rate(heplify_method_response{method=\"INVITE\", response=\"INVITE\"}[10m])) > 0.2) > 0.05",
     "legendFormat": "{{target_name}}"
    }
   ]
  },
  {
   "title": "INVITE 404",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum by(target_name) (rate(heplify_method_response{method=\"INVITE\", response=\"404\"}[10m])) / \nsum by(target_name) (rate(heplify_method_response{method=\"INVITE\", response=\"INVITE\"}[10m])) * 100 \nand sum by(target_name) (rate(heplify_method_response{method=\"INVITE\", response=\"INVITE\"}[10m])) > 0.2) > 1",
     "legendFormat": "{{target_name}}"
    }
   ]
  },
  {
   "title": "INVITE 482",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum by(target_name) (rate(heplify_method_response{method=\"INVITE\", response=~\"482\"}[10m])) / \nsum by(target_name) (rate(heplify_method_response{method=\"INVITE\", response=\"INVITE\"}[10m])) * 100 \nand sum by(target_name) (rate(heplify_method_response{method=\"INVITE\", response=\"INVITE\"}[10m])) > 0.2) > 0.2",
     "legendFormat": "{{target_name}}"
    }
   ]
  }
 ]
}